FROM frolvlad/alpine-glibc
# Environmental preparation
COPY ./build/libwasmer.so /lib
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib
RUN mkdir -p /root/.bitxhub/plugins
WORKDIR /root/.bitxhub

# Copy essential binaries from build
COPY ./build/bitxhub /usr/local/bin/
COPY ./build/raft.so ./plugins/

# Generate configuration
RUN bitxhub --repo=/root/.bitxhub init

EXPOSE 8881 60011 9091 53121 40011

CMD ["bitxhub", "start"]


