// Code generated by MockGen. DO NOT EDIT.
// Source: api.go
//
// Generated by this command:
//
//	mockgen -destination mock_api/mock_api.go -package mock_api -source api.go -typed
//
// Package mock_api is a generated GoMock package.
package mock_api

import (
	reflect "reflect"

	types "github.com/axiomesh/axiom-kit/types"
	api "github.com/axiomesh/axiom/internal/coreapi/api"
	common "github.com/axiomesh/axiom/internal/executor/system/common"
	events "github.com/axiomesh/axiom/pkg/model/events"
	vm "github.com/axiomesh/eth-kit/evm"
	ledger "github.com/axiomesh/eth-kit/ledger"
	common0 "github.com/ethereum/go-ethereum/common"
	event "github.com/ethereum/go-ethereum/event"
	gomock "go.uber.org/mock/gomock"
)

// MockCoreAPI is a mock of CoreAPI interface.
type MockCoreAPI struct {
	ctrl     *gomock.Controller
	recorder *MockCoreAPIMockRecorder
}

// MockCoreAPIMockRecorder is the mock recorder for MockCoreAPI.
type MockCoreAPIMockRecorder struct {
	mock *MockCoreAPI
}

// NewMockCoreAPI creates a new mock instance.
func NewMockCoreAPI(ctrl *gomock.Controller) *MockCoreAPI {
	mock := &MockCoreAPI{ctrl: ctrl}
	mock.recorder = &MockCoreAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoreAPI) EXPECT() *MockCoreAPIMockRecorder {
	return m.recorder
}

// Account mocks base method.
func (m *MockCoreAPI) Account() api.AccountAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Account")
	ret0, _ := ret[0].(api.AccountAPI)
	return ret0
}

// Account indicates an expected call of Account.
func (mr *MockCoreAPIMockRecorder) Account() *CoreAPIAccountCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Account", reflect.TypeOf((*MockCoreAPI)(nil).Account))
	return &CoreAPIAccountCall{Call: call}
}

// CoreAPIAccountCall wrap *gomock.Call
type CoreAPIAccountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *CoreAPIAccountCall) Return(arg0 api.AccountAPI) *CoreAPIAccountCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *CoreAPIAccountCall) Do(f func() api.AccountAPI) *CoreAPIAccountCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *CoreAPIAccountCall) DoAndReturn(f func() api.AccountAPI) *CoreAPIAccountCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Broker mocks base method.
func (m *MockCoreAPI) Broker() api.BrokerAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Broker")
	ret0, _ := ret[0].(api.BrokerAPI)
	return ret0
}

// Broker indicates an expected call of Broker.
func (mr *MockCoreAPIMockRecorder) Broker() *CoreAPIBrokerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broker", reflect.TypeOf((*MockCoreAPI)(nil).Broker))
	return &CoreAPIBrokerCall{Call: call}
}

// CoreAPIBrokerCall wrap *gomock.Call
type CoreAPIBrokerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *CoreAPIBrokerCall) Return(arg0 api.BrokerAPI) *CoreAPIBrokerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *CoreAPIBrokerCall) Do(f func() api.BrokerAPI) *CoreAPIBrokerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *CoreAPIBrokerCall) DoAndReturn(f func() api.BrokerAPI) *CoreAPIBrokerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Chain mocks base method.
func (m *MockCoreAPI) Chain() api.ChainAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chain")
	ret0, _ := ret[0].(api.ChainAPI)
	return ret0
}

// Chain indicates an expected call of Chain.
func (mr *MockCoreAPIMockRecorder) Chain() *CoreAPIChainCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chain", reflect.TypeOf((*MockCoreAPI)(nil).Chain))
	return &CoreAPIChainCall{Call: call}
}

// CoreAPIChainCall wrap *gomock.Call
type CoreAPIChainCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *CoreAPIChainCall) Return(arg0 api.ChainAPI) *CoreAPIChainCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *CoreAPIChainCall) Do(f func() api.ChainAPI) *CoreAPIChainCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *CoreAPIChainCall) DoAndReturn(f func() api.ChainAPI) *CoreAPIChainCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Feed mocks base method.
func (m *MockCoreAPI) Feed() api.FeedAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Feed")
	ret0, _ := ret[0].(api.FeedAPI)
	return ret0
}

// Feed indicates an expected call of Feed.
func (mr *MockCoreAPIMockRecorder) Feed() *CoreAPIFeedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Feed", reflect.TypeOf((*MockCoreAPI)(nil).Feed))
	return &CoreAPIFeedCall{Call: call}
}

// CoreAPIFeedCall wrap *gomock.Call
type CoreAPIFeedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *CoreAPIFeedCall) Return(arg0 api.FeedAPI) *CoreAPIFeedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *CoreAPIFeedCall) Do(f func() api.FeedAPI) *CoreAPIFeedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *CoreAPIFeedCall) DoAndReturn(f func() api.FeedAPI) *CoreAPIFeedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Gas mocks base method.
func (m *MockCoreAPI) Gas() api.GasAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gas")
	ret0, _ := ret[0].(api.GasAPI)
	return ret0
}

// Gas indicates an expected call of Gas.
func (mr *MockCoreAPIMockRecorder) Gas() *CoreAPIGasCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gas", reflect.TypeOf((*MockCoreAPI)(nil).Gas))
	return &CoreAPIGasCall{Call: call}
}

// CoreAPIGasCall wrap *gomock.Call
type CoreAPIGasCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *CoreAPIGasCall) Return(arg0 api.GasAPI) *CoreAPIGasCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *CoreAPIGasCall) Do(f func() api.GasAPI) *CoreAPIGasCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *CoreAPIGasCall) DoAndReturn(f func() api.GasAPI) *CoreAPIGasCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockBrokerAPI is a mock of BrokerAPI interface.
type MockBrokerAPI struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerAPIMockRecorder
}

// MockBrokerAPIMockRecorder is the mock recorder for MockBrokerAPI.
type MockBrokerAPIMockRecorder struct {
	mock *MockBrokerAPI
}

// NewMockBrokerAPI creates a new mock instance.
func NewMockBrokerAPI(ctrl *gomock.Controller) *MockBrokerAPI {
	mock := &MockBrokerAPI{ctrl: ctrl}
	mock.recorder = &MockBrokerAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerAPI) EXPECT() *MockBrokerAPIMockRecorder {
	return m.recorder
}

// GetBlock mocks base method.
func (m *MockBrokerAPI) GetBlock(mode, key string) (*types.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock", mode, key)
	ret0, _ := ret[0].(*types.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockBrokerAPIMockRecorder) GetBlock(mode, key any) *BrokerAPIGetBlockCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockBrokerAPI)(nil).GetBlock), mode, key)
	return &BrokerAPIGetBlockCall{Call: call}
}

// BrokerAPIGetBlockCall wrap *gomock.Call
type BrokerAPIGetBlockCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *BrokerAPIGetBlockCall) Return(arg0 *types.Block, arg1 error) *BrokerAPIGetBlockCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *BrokerAPIGetBlockCall) Do(f func(string, string) (*types.Block, error)) *BrokerAPIGetBlockCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *BrokerAPIGetBlockCall) DoAndReturn(f func(string, string) (*types.Block, error)) *BrokerAPIGetBlockCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetBlockHeaders mocks base method.
func (m *MockBrokerAPI) GetBlockHeaders(start, end uint64) ([]*types.BlockHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockHeaders", start, end)
	ret0, _ := ret[0].([]*types.BlockHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockHeaders indicates an expected call of GetBlockHeaders.
func (mr *MockBrokerAPIMockRecorder) GetBlockHeaders(start, end any) *BrokerAPIGetBlockHeadersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockHeaders", reflect.TypeOf((*MockBrokerAPI)(nil).GetBlockHeaders), start, end)
	return &BrokerAPIGetBlockHeadersCall{Call: call}
}

// BrokerAPIGetBlockHeadersCall wrap *gomock.Call
type BrokerAPIGetBlockHeadersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *BrokerAPIGetBlockHeadersCall) Return(arg0 []*types.BlockHeader, arg1 error) *BrokerAPIGetBlockHeadersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *BrokerAPIGetBlockHeadersCall) Do(f func(uint64, uint64) ([]*types.BlockHeader, error)) *BrokerAPIGetBlockHeadersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *BrokerAPIGetBlockHeadersCall) DoAndReturn(f func(uint64, uint64) ([]*types.BlockHeader, error)) *BrokerAPIGetBlockHeadersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetBlocks mocks base method.
func (m *MockBrokerAPI) GetBlocks(start, end uint64) ([]*types.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocks", start, end)
	ret0, _ := ret[0].([]*types.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocks indicates an expected call of GetBlocks.
func (mr *MockBrokerAPIMockRecorder) GetBlocks(start, end any) *BrokerAPIGetBlocksCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocks", reflect.TypeOf((*MockBrokerAPI)(nil).GetBlocks), start, end)
	return &BrokerAPIGetBlocksCall{Call: call}
}

// BrokerAPIGetBlocksCall wrap *gomock.Call
type BrokerAPIGetBlocksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *BrokerAPIGetBlocksCall) Return(arg0 []*types.Block, arg1 error) *BrokerAPIGetBlocksCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *BrokerAPIGetBlocksCall) Do(f func(uint64, uint64) ([]*types.Block, error)) *BrokerAPIGetBlocksCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *BrokerAPIGetBlocksCall) DoAndReturn(f func(uint64, uint64) ([]*types.Block, error)) *BrokerAPIGetBlocksCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetEvm mocks base method.
func (m *MockBrokerAPI) GetEvm(mes *vm.Message, vmConfig *vm.Config) (*vm.EVM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvm", mes, vmConfig)
	ret0, _ := ret[0].(*vm.EVM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvm indicates an expected call of GetEvm.
func (mr *MockBrokerAPIMockRecorder) GetEvm(mes, vmConfig any) *BrokerAPIGetEvmCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvm", reflect.TypeOf((*MockBrokerAPI)(nil).GetEvm), mes, vmConfig)
	return &BrokerAPIGetEvmCall{Call: call}
}

// BrokerAPIGetEvmCall wrap *gomock.Call
type BrokerAPIGetEvmCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *BrokerAPIGetEvmCall) Return(arg0 *vm.EVM, arg1 error) *BrokerAPIGetEvmCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *BrokerAPIGetEvmCall) Do(f func(*vm.Message, *vm.Config) (*vm.EVM, error)) *BrokerAPIGetEvmCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *BrokerAPIGetEvmCall) DoAndReturn(f func(*vm.Message, *vm.Config) (*vm.EVM, error)) *BrokerAPIGetEvmCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPendingNonceByAccount mocks base method.
func (m *MockBrokerAPI) GetPendingNonceByAccount(account string) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingNonceByAccount", account)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetPendingNonceByAccount indicates an expected call of GetPendingNonceByAccount.
func (mr *MockBrokerAPIMockRecorder) GetPendingNonceByAccount(account any) *BrokerAPIGetPendingNonceByAccountCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingNonceByAccount", reflect.TypeOf((*MockBrokerAPI)(nil).GetPendingNonceByAccount), account)
	return &BrokerAPIGetPendingNonceByAccountCall{Call: call}
}

// BrokerAPIGetPendingNonceByAccountCall wrap *gomock.Call
type BrokerAPIGetPendingNonceByAccountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *BrokerAPIGetPendingNonceByAccountCall) Return(arg0 uint64) *BrokerAPIGetPendingNonceByAccountCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *BrokerAPIGetPendingNonceByAccountCall) Do(f func(string) uint64) *BrokerAPIGetPendingNonceByAccountCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *BrokerAPIGetPendingNonceByAccountCall) DoAndReturn(f func(string) uint64) *BrokerAPIGetPendingNonceByAccountCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPoolTransaction mocks base method.
func (m *MockBrokerAPI) GetPoolTransaction(hash *types.Hash) *types.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPoolTransaction", hash)
	ret0, _ := ret[0].(*types.Transaction)
	return ret0
}

// GetPoolTransaction indicates an expected call of GetPoolTransaction.
func (mr *MockBrokerAPIMockRecorder) GetPoolTransaction(hash any) *BrokerAPIGetPoolTransactionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPoolTransaction", reflect.TypeOf((*MockBrokerAPI)(nil).GetPoolTransaction), hash)
	return &BrokerAPIGetPoolTransactionCall{Call: call}
}

// BrokerAPIGetPoolTransactionCall wrap *gomock.Call
type BrokerAPIGetPoolTransactionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *BrokerAPIGetPoolTransactionCall) Return(arg0 *types.Transaction) *BrokerAPIGetPoolTransactionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *BrokerAPIGetPoolTransactionCall) Do(f func(*types.Hash) *types.Transaction) *BrokerAPIGetPoolTransactionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *BrokerAPIGetPoolTransactionCall) DoAndReturn(f func(*types.Hash) *types.Transaction) *BrokerAPIGetPoolTransactionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetReceipt mocks base method.
func (m *MockBrokerAPI) GetReceipt(arg0 *types.Hash) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceipt", arg0)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceipt indicates an expected call of GetReceipt.
func (mr *MockBrokerAPIMockRecorder) GetReceipt(arg0 any) *BrokerAPIGetReceiptCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceipt", reflect.TypeOf((*MockBrokerAPI)(nil).GetReceipt), arg0)
	return &BrokerAPIGetReceiptCall{Call: call}
}

// BrokerAPIGetReceiptCall wrap *gomock.Call
type BrokerAPIGetReceiptCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *BrokerAPIGetReceiptCall) Return(arg0 *types.Receipt, arg1 error) *BrokerAPIGetReceiptCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *BrokerAPIGetReceiptCall) Do(f func(*types.Hash) (*types.Receipt, error)) *BrokerAPIGetReceiptCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *BrokerAPIGetReceiptCall) DoAndReturn(f func(*types.Hash) (*types.Receipt, error)) *BrokerAPIGetReceiptCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetStateLedger mocks base method.
func (m *MockBrokerAPI) GetStateLedger() ledger.StateLedger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStateLedger")
	ret0, _ := ret[0].(ledger.StateLedger)
	return ret0
}

// GetStateLedger indicates an expected call of GetStateLedger.
func (mr *MockBrokerAPIMockRecorder) GetStateLedger() *BrokerAPIGetStateLedgerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStateLedger", reflect.TypeOf((*MockBrokerAPI)(nil).GetStateLedger))
	return &BrokerAPIGetStateLedgerCall{Call: call}
}

// BrokerAPIGetStateLedgerCall wrap *gomock.Call
type BrokerAPIGetStateLedgerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *BrokerAPIGetStateLedgerCall) Return(arg0 ledger.StateLedger) *BrokerAPIGetStateLedgerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *BrokerAPIGetStateLedgerCall) Do(f func() ledger.StateLedger) *BrokerAPIGetStateLedgerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *BrokerAPIGetStateLedgerCall) DoAndReturn(f func() ledger.StateLedger) *BrokerAPIGetStateLedgerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSystemContract mocks base method.
func (m *MockBrokerAPI) GetSystemContract(addr *common0.Address) (common.SystemContract, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemContract", addr)
	ret0, _ := ret[0].(common.SystemContract)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSystemContract indicates an expected call of GetSystemContract.
func (mr *MockBrokerAPIMockRecorder) GetSystemContract(addr any) *BrokerAPIGetSystemContractCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemContract", reflect.TypeOf((*MockBrokerAPI)(nil).GetSystemContract), addr)
	return &BrokerAPIGetSystemContractCall{Call: call}
}

// BrokerAPIGetSystemContractCall wrap *gomock.Call
type BrokerAPIGetSystemContractCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *BrokerAPIGetSystemContractCall) Return(arg0 common.SystemContract, arg1 bool) *BrokerAPIGetSystemContractCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *BrokerAPIGetSystemContractCall) Do(f func(*common0.Address) (common.SystemContract, bool)) *BrokerAPIGetSystemContractCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *BrokerAPIGetSystemContractCall) DoAndReturn(f func(*common0.Address) (common.SystemContract, bool)) *BrokerAPIGetSystemContractCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTransaction mocks base method.
func (m *MockBrokerAPI) GetTransaction(arg0 *types.Hash) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", arg0)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockBrokerAPIMockRecorder) GetTransaction(arg0 any) *BrokerAPIGetTransactionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockBrokerAPI)(nil).GetTransaction), arg0)
	return &BrokerAPIGetTransactionCall{Call: call}
}

// BrokerAPIGetTransactionCall wrap *gomock.Call
type BrokerAPIGetTransactionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *BrokerAPIGetTransactionCall) Return(arg0 *types.Transaction, arg1 error) *BrokerAPIGetTransactionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *BrokerAPIGetTransactionCall) Do(f func(*types.Hash) (*types.Transaction, error)) *BrokerAPIGetTransactionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *BrokerAPIGetTransactionCall) DoAndReturn(f func(*types.Hash) (*types.Transaction, error)) *BrokerAPIGetTransactionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTransactionMeta mocks base method.
func (m *MockBrokerAPI) GetTransactionMeta(arg0 *types.Hash) (*types.TransactionMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionMeta", arg0)
	ret0, _ := ret[0].(*types.TransactionMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionMeta indicates an expected call of GetTransactionMeta.
func (mr *MockBrokerAPIMockRecorder) GetTransactionMeta(arg0 any) *BrokerAPIGetTransactionMetaCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionMeta", reflect.TypeOf((*MockBrokerAPI)(nil).GetTransactionMeta), arg0)
	return &BrokerAPIGetTransactionMetaCall{Call: call}
}

// BrokerAPIGetTransactionMetaCall wrap *gomock.Call
type BrokerAPIGetTransactionMetaCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *BrokerAPIGetTransactionMetaCall) Return(arg0 *types.TransactionMeta, arg1 error) *BrokerAPIGetTransactionMetaCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *BrokerAPIGetTransactionMetaCall) Do(f func(*types.Hash) (*types.TransactionMeta, error)) *BrokerAPIGetTransactionMetaCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *BrokerAPIGetTransactionMetaCall) DoAndReturn(f func(*types.Hash) (*types.TransactionMeta, error)) *BrokerAPIGetTransactionMetaCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HandleTransaction mocks base method.
func (m *MockBrokerAPI) HandleTransaction(tx *types.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleTransaction", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleTransaction indicates an expected call of HandleTransaction.
func (mr *MockBrokerAPIMockRecorder) HandleTransaction(tx any) *BrokerAPIHandleTransactionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTransaction", reflect.TypeOf((*MockBrokerAPI)(nil).HandleTransaction), tx)
	return &BrokerAPIHandleTransactionCall{Call: call}
}

// BrokerAPIHandleTransactionCall wrap *gomock.Call
type BrokerAPIHandleTransactionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *BrokerAPIHandleTransactionCall) Return(arg0 error) *BrokerAPIHandleTransactionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *BrokerAPIHandleTransactionCall) Do(f func(*types.Transaction) error) *BrokerAPIHandleTransactionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *BrokerAPIHandleTransactionCall) DoAndReturn(f func(*types.Transaction) error) *BrokerAPIHandleTransactionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HandleView mocks base method.
func (m *MockBrokerAPI) HandleView(tx *types.Transaction) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleView", tx)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleView indicates an expected call of HandleView.
func (mr *MockBrokerAPIMockRecorder) HandleView(tx any) *BrokerAPIHandleViewCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleView", reflect.TypeOf((*MockBrokerAPI)(nil).HandleView), tx)
	return &BrokerAPIHandleViewCall{Call: call}
}

// BrokerAPIHandleViewCall wrap *gomock.Call
type BrokerAPIHandleViewCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *BrokerAPIHandleViewCall) Return(arg0 *types.Receipt, arg1 error) *BrokerAPIHandleViewCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *BrokerAPIHandleViewCall) Do(f func(*types.Transaction) (*types.Receipt, error)) *BrokerAPIHandleViewCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *BrokerAPIHandleViewCall) DoAndReturn(f func(*types.Transaction) (*types.Receipt, error)) *BrokerAPIHandleViewCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OrderReady mocks base method.
func (m *MockBrokerAPI) OrderReady() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderReady")
	ret0, _ := ret[0].(error)
	return ret0
}

// OrderReady indicates an expected call of OrderReady.
func (mr *MockBrokerAPIMockRecorder) OrderReady() *BrokerAPIOrderReadyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderReady", reflect.TypeOf((*MockBrokerAPI)(nil).OrderReady))
	return &BrokerAPIOrderReadyCall{Call: call}
}

// BrokerAPIOrderReadyCall wrap *gomock.Call
type BrokerAPIOrderReadyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *BrokerAPIOrderReadyCall) Return(arg0 error) *BrokerAPIOrderReadyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *BrokerAPIOrderReadyCall) Do(f func() error) *BrokerAPIOrderReadyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *BrokerAPIOrderReadyCall) DoAndReturn(f func() error) *BrokerAPIOrderReadyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockNetworkAPI is a mock of NetworkAPI interface.
type MockNetworkAPI struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkAPIMockRecorder
}

// MockNetworkAPIMockRecorder is the mock recorder for MockNetworkAPI.
type MockNetworkAPIMockRecorder struct {
	mock *MockNetworkAPI
}

// NewMockNetworkAPI creates a new mock instance.
func NewMockNetworkAPI(ctrl *gomock.Controller) *MockNetworkAPI {
	mock := &MockNetworkAPI{ctrl: ctrl}
	mock.recorder = &MockNetworkAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkAPI) EXPECT() *MockNetworkAPIMockRecorder {
	return m.recorder
}

// PeerInfo mocks base method.
func (m *MockNetworkAPI) PeerInfo() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PeerInfo")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PeerInfo indicates an expected call of PeerInfo.
func (mr *MockNetworkAPIMockRecorder) PeerInfo() *NetworkAPIPeerInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PeerInfo", reflect.TypeOf((*MockNetworkAPI)(nil).PeerInfo))
	return &NetworkAPIPeerInfoCall{Call: call}
}

// NetworkAPIPeerInfoCall wrap *gomock.Call
type NetworkAPIPeerInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *NetworkAPIPeerInfoCall) Return(arg0 []byte, arg1 error) *NetworkAPIPeerInfoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *NetworkAPIPeerInfoCall) Do(f func() ([]byte, error)) *NetworkAPIPeerInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *NetworkAPIPeerInfoCall) DoAndReturn(f func() ([]byte, error)) *NetworkAPIPeerInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockChainAPI is a mock of ChainAPI interface.
type MockChainAPI struct {
	ctrl     *gomock.Controller
	recorder *MockChainAPIMockRecorder
}

// MockChainAPIMockRecorder is the mock recorder for MockChainAPI.
type MockChainAPIMockRecorder struct {
	mock *MockChainAPI
}

// NewMockChainAPI creates a new mock instance.
func NewMockChainAPI(ctrl *gomock.Controller) *MockChainAPI {
	mock := &MockChainAPI{ctrl: ctrl}
	mock.recorder = &MockChainAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChainAPI) EXPECT() *MockChainAPIMockRecorder {
	return m.recorder
}

// Meta mocks base method.
func (m *MockChainAPI) Meta() (*types.ChainMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Meta")
	ret0, _ := ret[0].(*types.ChainMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Meta indicates an expected call of Meta.
func (mr *MockChainAPIMockRecorder) Meta() *ChainAPIMetaCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Meta", reflect.TypeOf((*MockChainAPI)(nil).Meta))
	return &ChainAPIMetaCall{Call: call}
}

// ChainAPIMetaCall wrap *gomock.Call
type ChainAPIMetaCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ChainAPIMetaCall) Return(arg0 *types.ChainMeta, arg1 error) *ChainAPIMetaCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ChainAPIMetaCall) Do(f func() (*types.ChainMeta, error)) *ChainAPIMetaCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ChainAPIMetaCall) DoAndReturn(f func() (*types.ChainMeta, error)) *ChainAPIMetaCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Status mocks base method.
func (m *MockChainAPI) Status() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(string)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockChainAPIMockRecorder) Status() *ChainAPIStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockChainAPI)(nil).Status))
	return &ChainAPIStatusCall{Call: call}
}

// ChainAPIStatusCall wrap *gomock.Call
type ChainAPIStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ChainAPIStatusCall) Return(arg0 string) *ChainAPIStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ChainAPIStatusCall) Do(f func() string) *ChainAPIStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ChainAPIStatusCall) DoAndReturn(f func() string) *ChainAPIStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TPS mocks base method.
func (m *MockChainAPI) TPS(begin, end uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TPS", begin, end)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TPS indicates an expected call of TPS.
func (mr *MockChainAPIMockRecorder) TPS(begin, end any) *ChainAPITPSCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TPS", reflect.TypeOf((*MockChainAPI)(nil).TPS), begin, end)
	return &ChainAPITPSCall{Call: call}
}

// ChainAPITPSCall wrap *gomock.Call
type ChainAPITPSCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ChainAPITPSCall) Return(arg0 uint64, arg1 error) *ChainAPITPSCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ChainAPITPSCall) Do(f func(uint64, uint64) (uint64, error)) *ChainAPITPSCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ChainAPITPSCall) DoAndReturn(f func(uint64, uint64) (uint64, error)) *ChainAPITPSCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockFeedAPI is a mock of FeedAPI interface.
type MockFeedAPI struct {
	ctrl     *gomock.Controller
	recorder *MockFeedAPIMockRecorder
}

// MockFeedAPIMockRecorder is the mock recorder for MockFeedAPI.
type MockFeedAPIMockRecorder struct {
	mock *MockFeedAPI
}

// NewMockFeedAPI creates a new mock instance.
func NewMockFeedAPI(ctrl *gomock.Controller) *MockFeedAPI {
	mock := &MockFeedAPI{ctrl: ctrl}
	mock.recorder = &MockFeedAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedAPI) EXPECT() *MockFeedAPIMockRecorder {
	return m.recorder
}

// BloomStatus mocks base method.
func (m *MockFeedAPI) BloomStatus() (uint64, uint64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BloomStatus")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	return ret0, ret1
}

// BloomStatus indicates an expected call of BloomStatus.
func (mr *MockFeedAPIMockRecorder) BloomStatus() *FeedAPIBloomStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BloomStatus", reflect.TypeOf((*MockFeedAPI)(nil).BloomStatus))
	return &FeedAPIBloomStatusCall{Call: call}
}

// FeedAPIBloomStatusCall wrap *gomock.Call
type FeedAPIBloomStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *FeedAPIBloomStatusCall) Return(arg0, arg1 uint64) *FeedAPIBloomStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *FeedAPIBloomStatusCall) Do(f func() (uint64, uint64)) *FeedAPIBloomStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *FeedAPIBloomStatusCall) DoAndReturn(f func() (uint64, uint64)) *FeedAPIBloomStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubscribeLogsEvent mocks base method.
func (m *MockFeedAPI) SubscribeLogsEvent(arg0 chan<- []*types.EvmLog) event.Subscription {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeLogsEvent", arg0)
	ret0, _ := ret[0].(event.Subscription)
	return ret0
}

// SubscribeLogsEvent indicates an expected call of SubscribeLogsEvent.
func (mr *MockFeedAPIMockRecorder) SubscribeLogsEvent(arg0 any) *FeedAPISubscribeLogsEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeLogsEvent", reflect.TypeOf((*MockFeedAPI)(nil).SubscribeLogsEvent), arg0)
	return &FeedAPISubscribeLogsEventCall{Call: call}
}

// FeedAPISubscribeLogsEventCall wrap *gomock.Call
type FeedAPISubscribeLogsEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *FeedAPISubscribeLogsEventCall) Return(arg0 event.Subscription) *FeedAPISubscribeLogsEventCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *FeedAPISubscribeLogsEventCall) Do(f func(chan<- []*types.EvmLog) event.Subscription) *FeedAPISubscribeLogsEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *FeedAPISubscribeLogsEventCall) DoAndReturn(f func(chan<- []*types.EvmLog) event.Subscription) *FeedAPISubscribeLogsEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubscribeNewBlockEvent mocks base method.
func (m *MockFeedAPI) SubscribeNewBlockEvent(arg0 chan<- events.ExecutedEvent) event.Subscription {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeNewBlockEvent", arg0)
	ret0, _ := ret[0].(event.Subscription)
	return ret0
}

// SubscribeNewBlockEvent indicates an expected call of SubscribeNewBlockEvent.
func (mr *MockFeedAPIMockRecorder) SubscribeNewBlockEvent(arg0 any) *FeedAPISubscribeNewBlockEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeNewBlockEvent", reflect.TypeOf((*MockFeedAPI)(nil).SubscribeNewBlockEvent), arg0)
	return &FeedAPISubscribeNewBlockEventCall{Call: call}
}

// FeedAPISubscribeNewBlockEventCall wrap *gomock.Call
type FeedAPISubscribeNewBlockEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *FeedAPISubscribeNewBlockEventCall) Return(arg0 event.Subscription) *FeedAPISubscribeNewBlockEventCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *FeedAPISubscribeNewBlockEventCall) Do(f func(chan<- events.ExecutedEvent) event.Subscription) *FeedAPISubscribeNewBlockEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *FeedAPISubscribeNewBlockEventCall) DoAndReturn(f func(chan<- events.ExecutedEvent) event.Subscription) *FeedAPISubscribeNewBlockEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubscribeNewTxEvent mocks base method.
func (m *MockFeedAPI) SubscribeNewTxEvent(arg0 chan<- []*types.Transaction) event.Subscription {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeNewTxEvent", arg0)
	ret0, _ := ret[0].(event.Subscription)
	return ret0
}

// SubscribeNewTxEvent indicates an expected call of SubscribeNewTxEvent.
func (mr *MockFeedAPIMockRecorder) SubscribeNewTxEvent(arg0 any) *FeedAPISubscribeNewTxEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeNewTxEvent", reflect.TypeOf((*MockFeedAPI)(nil).SubscribeNewTxEvent), arg0)
	return &FeedAPISubscribeNewTxEventCall{Call: call}
}

// FeedAPISubscribeNewTxEventCall wrap *gomock.Call
type FeedAPISubscribeNewTxEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *FeedAPISubscribeNewTxEventCall) Return(arg0 event.Subscription) *FeedAPISubscribeNewTxEventCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *FeedAPISubscribeNewTxEventCall) Do(f func(chan<- []*types.Transaction) event.Subscription) *FeedAPISubscribeNewTxEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *FeedAPISubscribeNewTxEventCall) DoAndReturn(f func(chan<- []*types.Transaction) event.Subscription) *FeedAPISubscribeNewTxEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockAccountAPI is a mock of AccountAPI interface.
type MockAccountAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAccountAPIMockRecorder
}

// MockAccountAPIMockRecorder is the mock recorder for MockAccountAPI.
type MockAccountAPIMockRecorder struct {
	mock *MockAccountAPI
}

// NewMockAccountAPI creates a new mock instance.
func NewMockAccountAPI(ctrl *gomock.Controller) *MockAccountAPI {
	mock := &MockAccountAPI{ctrl: ctrl}
	mock.recorder = &MockAccountAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountAPI) EXPECT() *MockAccountAPIMockRecorder {
	return m.recorder
}

// GetAccount mocks base method.
func (m *MockAccountAPI) GetAccount(addr *types.Address) ledger.IAccount {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", addr)
	ret0, _ := ret[0].(ledger.IAccount)
	return ret0
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockAccountAPIMockRecorder) GetAccount(addr any) *AccountAPIGetAccountCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockAccountAPI)(nil).GetAccount), addr)
	return &AccountAPIGetAccountCall{Call: call}
}

// AccountAPIGetAccountCall wrap *gomock.Call
type AccountAPIGetAccountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *AccountAPIGetAccountCall) Return(arg0 ledger.IAccount) *AccountAPIGetAccountCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *AccountAPIGetAccountCall) Do(f func(*types.Address) ledger.IAccount) *AccountAPIGetAccountCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *AccountAPIGetAccountCall) DoAndReturn(f func(*types.Address) ledger.IAccount) *AccountAPIGetAccountCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockGasAPI is a mock of GasAPI interface.
type MockGasAPI struct {
	ctrl     *gomock.Controller
	recorder *MockGasAPIMockRecorder
}

// MockGasAPIMockRecorder is the mock recorder for MockGasAPI.
type MockGasAPIMockRecorder struct {
	mock *MockGasAPI
}

// NewMockGasAPI creates a new mock instance.
func NewMockGasAPI(ctrl *gomock.Controller) *MockGasAPI {
	mock := &MockGasAPI{ctrl: ctrl}
	mock.recorder = &MockGasAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGasAPI) EXPECT() *MockGasAPIMockRecorder {
	return m.recorder
}

// GetCurrentGasPrice mocks base method.
func (m *MockGasAPI) GetCurrentGasPrice(blockHeight uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentGasPrice", blockHeight)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentGasPrice indicates an expected call of GetCurrentGasPrice.
func (mr *MockGasAPIMockRecorder) GetCurrentGasPrice(blockHeight any) *GasAPIGetCurrentGasPriceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentGasPrice", reflect.TypeOf((*MockGasAPI)(nil).GetCurrentGasPrice), blockHeight)
	return &GasAPIGetCurrentGasPriceCall{Call: call}
}

// GasAPIGetCurrentGasPriceCall wrap *gomock.Call
type GasAPIGetCurrentGasPriceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GasAPIGetCurrentGasPriceCall) Return(arg0 uint64, arg1 error) *GasAPIGetCurrentGasPriceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GasAPIGetCurrentGasPriceCall) Do(f func(uint64) (uint64, error)) *GasAPIGetCurrentGasPriceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GasAPIGetCurrentGasPriceCall) DoAndReturn(f func(uint64) (uint64, error)) *GasAPIGetCurrentGasPriceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetGasPrice mocks base method.
func (m *MockGasAPI) GetGasPrice() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGasPrice")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGasPrice indicates an expected call of GetGasPrice.
func (mr *MockGasAPIMockRecorder) GetGasPrice() *GasAPIGetGasPriceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGasPrice", reflect.TypeOf((*MockGasAPI)(nil).GetGasPrice))
	return &GasAPIGetGasPriceCall{Call: call}
}

// GasAPIGetGasPriceCall wrap *gomock.Call
type GasAPIGetGasPriceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GasAPIGetGasPriceCall) Return(arg0 uint64, arg1 error) *GasAPIGetGasPriceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GasAPIGetGasPriceCall) Do(f func() (uint64, error)) *GasAPIGetGasPriceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GasAPIGetGasPriceCall) DoAndReturn(f func() (uint64, error)) *GasAPIGetGasPriceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
